print("Melancholy".endswith("ly"))
print("R2D2".isalnum())
print("C3PO".isalpha())
print("X-wing".isascii())
print("0456 784 907".isdecimal())
print("0345".isdigit())
print("first_name".isidentifier())
print("Juxtaposition".islower())
print("45".isnumeric())
print("\nhello".isprintable())
print("  ".isspace())
print("Ethereal".istitle())
print("Maelstrom".isupper())
print("Luminescent".startswith("le"))